---
- name: Modify DC2 s2-core1/core2 Configurations
  hosts: dc2_dci
  tasks:

    - name: Import Global Vars
      include_vars: "{{ item }}"
      with_items:
        - "../global_vars/global_dc_vars.yml"

    - name: load configuration from file
      arista.eos.eos_config:
        src: ../sites/dc2/dci_configs/{{inventory_hostname}}.cfg