---
- name: Deploy DC1 Configurations via EAPI
  hosts: dc1_fabric
  gather_facts: false
  tasks:

    - name: Deploy Configuration to Device
      import_role:
         name: arista.avd.eos_config_deploy_eapi