---
- name: Deploying DC2 Changes via CVP
  hosts: cvp
  connection: local
  tasks:
    - name: run CVP provisioning
      import_role:
          name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: 'dc2_fabric'
        state: present
        cv_collection: v3
        execute_tasks: true