---
- name: Deploy DC2 Configurations via EAPI
  hosts: dc2_fabric
  gather_facts: false
  tasks:

    - name: Deploy Configuration to Device
      import_role:
         name: arista.avd.eos_config_deploy_eapi