---
- name: Deploying DC1 Changes via CVP
  hosts: cvp
  connection: local
  tasks:
    - name: Import Global Vars
      include_vars: "{{ item }}"
      with_items:
        - "../global_vars/global_dc_vars.yml"

    - name: run CVP provisioning
      import_role:
          name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: 'dc1_fabric'
        state: present
        cv_collection: v3
        execute_tasks: true